version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/cdh-docker
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/opensource-docker
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
