repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: name-tests-test
    - id: requirements-txt-fixer
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.20.1
  hooks:
    - id: setup-cfg-fmt
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.8.1
  hooks:
    - id: reorder-python-imports
      args: [--py37-plus, --add-import, 'from __future__ import annotations']
- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.2.3
  hooks:
    - id: add-trailing-comma
      args: [--py36-plus]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.37.2
  hooks:
    - id: pyupgrade
      args: [--py37-plus]
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.6.0
  hooks:
    - id: autopep8
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.961
  hooks:
    - id: mypy

- repo: https://github.com/asottile/pyupgrade
  rev: v2.37.2
  hooks:
    - id: pyupgrade
