name: HiBench CI SPARK_2.4_HADOOP_2.7

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up JDK 1.8
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
        with:
          java-version: 1.8
      - name: Restore cached dependencies
        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
        with:
          path: |
            # /var/cache/apt/archives/*.deb
            ~/.m2/repository
            ~/opt
          key: ${{ runner.os }}_spark_2.4_hadoop_2.7
          restore-keys: |
            ${{ runner.os }}-
      - name: Cluster spark_2.4_hadoop_2.7_hive_0.14
        run: |
          ${{github.workspace}}/actions/build_and_run_all_spark_2.4_hadoop_2.7_hive_0.14_part_1.sh
