name: HiBench CI SPARK_3.0_HADOOP_3.2

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            # /var/cache/apt/archives/*.deb
            ~/.m2/repository
            ~/opt
          key: ${{ runner.os }}_spark_3.0_hadoop_3.2
          restore-keys: |
            ${{ runner.os }}-
      - name: Cluster spark_3.0_hadoop_3.2_hive_3.0
        run: |
          ${{github.workspace}}/actions/build_and_run_all_spark_3.0_hadoop_3.2.sh
